- LDMP/help/source/documentation/calculate.rst
adding citation for good practice guidelines
> updates to source: calculate

- LDMP/data/gee_datasets.json
can link the dataset directly to the license
> adding license and license URL to these posts

- LDMP/help/source/training/video_links.rst
added videos from Mariano to YouTube and updated the links here to reflect the latest version of the toolbox
> updating videos for Trends.Earth website instructions

- LDMP/i18n/LDMP.ar.ts
- LDMP/i18n/LDMP.es.ts
- LDMP/i18n/LDMP.fr.ts
- LDMP/i18n/LDMP.pt.ts
- LDMP/i18n/LDMP.ru.ts
- LDMP/i18n/LDMP.sw.ts
- LDMP/i18n/LDMP.ts
- LDMP/i18n/LDMP.zh.ts
- LDMP/settings.py
Fix minor typo in welcome message, changing sutainable to sustainable
> Fix sutainable typo

- README.md
- tasks.py
little fix to allow plugin building using invoke. Tasks help weren't aligned to tasks signatures
> Aligned task help to task signature

- LDMP/__init__.py
- LDMP/calculate_lc.py
- LDMP/calculate_soc.py
- LDMP/calculate_tc.py
- LDMP/gui/DlgSettings.ui
- LDMP/gui/WidgetSettingsAdvanced.ui
- LDMP/jobs.py
- LDMP/settings.py
> Advanced parameters refactoring in the Settings dialogue. Fixes #359

- LDMP/__init__.py
- LDMP/gui/DlgSettings.ui
- LDMP/gui/WidgetSelectArea.ui
- LDMP/settings.py
Fixes https://github.com/ConservationInternational/trends.earth/issues/368
Screenshot
> add name for region settings

- LDMP/gui/WidgetSelectArea.ui
- LDMP/settings.py
Fixes https://github.com/ConservationInternational/trends.earth/issues/378
> Update on area name value when opening settings for first time.

- LDMP/__init__.py
- LDMP/gui/WidgetAlgorithmLeaf.ui
- LDMP/gui/WidgetMain.ui
- LDMP/main_widget.py
- LDMP/models/algorithms.py
- LDMP/models/algorithms_delegate.py
- LDMP/models/algorithms_model.py
- LDMP/test/gui/algorithm_tree_test.py
Implemented MVC to show algorithms with custom delegate to trigger run actions
TODO:
1) Groups has a basic moving pixmap. better would be using SVG animation => need more investigation and test to do it at work with QSvgPainter or something equivalent.
2) Need a better graphic organization... UX is too basic and need more work for better representation of delegated widget
3) For now algorithms are fixed as test data. Need a way to load algorithm list from a conf file and setup model
Teh code is flexible enough to allow:
1) discriminate editing basing on row/column index
2) can create a custom widget editor (and rendered when not in editing) for each row/column index
all modification should be limited (almost completely) inside the algorithm view delegate.
fixes #367
> MVC implemented. Fixes #367

- LDMP/calculate.py
- LDMP/gui/WidgetAlgorithmLeaf.ui
- LDMP/gui/WidgetMain.ui
- LDMP/main_widget.py
- LDMP/models/algorithms.py
- LDMP/models/algorithms_delegate.py
- LDMP/models/algorithms_model.py
- LDMP/test/gui/algorithm_tree_test.py
New list of algorithms following 1/1 the original interface
fixes #386
> New list of algorithms

- LDMP/__init__.py
- LDMP/calculate.py
- LDMP/settings.py
- LDMP/summary.py
> Cast to bool boolean key in the ini file. Fixes #389

- LDMP/gui/WidgetMain.ui
- LDMP/main_widget.py
Fixes https://github.com/ConservationInternational/trends.earth/issues/404
Screenshot
> Add load base map button in datasets tab

- LDMP/main_widget.py
Fixes https://github.com/ConservationInternational/trends.earth/issues/413
> Add Icon for load base map button

- LDMP/main_widget.py
Fixes https://github.com/ConservationInternational/trends.earth/issues/405
>  Hook remote data download button

- LDMP/main_widget.py
Fixes https://github.com/ConservationInternational/trends.earth/issues/406
> Hook local data import button

- LDMP/jobs.py
- LDMP/models/datasets.py
- LDMP/models/datasets_delegate.py
Add a dataset to canvas. fixes https://github.com/ConservationInternational/trends.earth/issues/402
> Dataset add

- LDMP/gui/WidgetDatasetItem.ui
- LDMP/gui/WidgetMain.ui
- LDMP/main_widget.py
Fixes https://github.com/ConservationInternational/trends.earth/issues/424.
Adds tooltips to widgets on the UI.
> Adding tooltips

- LDMP/main_widget.py
> Reduce dock widget startup instantiating GUI at plugin load. Fixes #390

- LDMP/calculate.py
- LDMP/calculate_lc.py
- LDMP/calculate_ldn.py
- LDMP/conf.py
- LDMP/jobs/models.py
- LDMP/lc_setup.py
- LDMP/localexecution/landcover.py
- LDMP/localexecution/ldn.py
- LDMP/utils.py
This PR adds support for calculating SDG 15.3.1 Land Cover sub-indicator locally
> Allow calculating land cover sub-indicator locally

- LDMP/calculate_lc.py
- LDMP/calculate_soc.py
- LDMP/conf.py
- LDMP/gui/WidgetMain.ui
- LDMP/localexecution/landcover.py
- LDMP/localexecution/ldn.py
- LDMP/localexecution/soilorganiccarbon.py
- LDMP/utils.py
This PR adds support for running the Soil Organic Carbon algorithm locally
> Implement support for running Soil Organic Carbon locally

- LDMP/calculate_lc.py
- LDMP/calculate_urban.py
- LDMP/conf.py
- LDMP/localexecution/ldn.py
- LDMP/localexecution/urbanchange.py
- LDMP/utils.py
This PR implements support for running the calculations of SDG 11.3.1. locally
> Implement support for running SDG 11.3.1 summary table locally

- LDMP/calculate_rest_biomass.py
- LDMP/calculate_tc.py
- LDMP/conf.py
- LDMP/jobs/manager.py
- LDMP/jobs/mvc.py
- LDMP/localexecution/totalcarbon.py
This PR adds support for running:
- experimental algorithms remotely
- total carbon summary table locally
> Add support for local total carbon summary table calculations

- LDMP/calculate_rest_biomass.py
- LDMP/conf.py
- LDMP/localexecution/biomassrestoration.py
- LDMP/localexecution/urbanchange.py
This PR adds support for local calculations of the biomass restoration summary table algorithm
> Add support for local biomass restoration summary table calculations

- LDMP/datasets_dialog.py
Fixes https://github.com/ConservationInternational/trends.earth/issues/455
> Close the datasets details dialog when dataset is being loaded into QGIS

- LDMP/algorithms/mvc.py
- LDMP/conf.py
- LDMP/gui/WidgetAlgorithmLeaf.ui
This PR tweaks the look of the algorithm list item in order to provide more space for the algorithm's brief description.
> allow adjusting description label size

- LDMP/calculate.py
> Fixes broken collapse button on algorithm execution dialogues

- LDMP/data_io.py
> Add region name and creation date to combo box description

- LDMP/gui/WidgetMain.ui
- LDMP/jobs/mvc.py
- LDMP/main_widget.py
Fixes https://github.com/ConservationInternational/trends.earth/issues/457
> Removed dynamic sorting functionality

- LDMP/gui/DlgCalculateLC.ui
- LDMP/gui/DlgCalculateLDNSummaryTableAdmin.ui
- LDMP/gui/DlgCalculateOneStep.ui
- LDMP/gui/DlgCalculateProd.ui
- LDMP/gui/DlgCalculateRestBiomassData.ui
- LDMP/gui/DlgCalculateRestBiomassSummaryTable.ui
- LDMP/gui/DlgCalculateSOC.ui
- LDMP/gui/DlgCalculateTCData.ui
- LDMP/gui/DlgCalculateTCSummaryTable.ui
- LDMP/gui/DlgCalculateUrbanData.ui
- LDMP/gui/DlgCalculateUrbanSummaryTable.ui
- LDMP/gui/land_cover_setup_widget.ui
- LDMP/gui/land_cover_setup_widget_local.ui
Fixes https://github.com/ConservationInternational/trends.earth/issues/458 and https://github.com/ConservationInternational/trends.earth/issues/477
> Tooltips updates

- LDMP/algorithms/models.py
- LDMP/algorithms/mvc.py
- LDMP/conf.py
Fixes https://github.com/ConservationInternational/trends.earth/issues/489
Updated location and style for the SDG 15.3.1 sub-indicators in one step and the main SDG 15.3.1 indicator algorithms
New algorithms tree view UI
> Update on algorithms tree view

- LDMP/__init__.py
- LDMP/about.py
- LDMP/algorithms/mvc.py
- LDMP/api.py
- LDMP/auth.py
- LDMP/calculate.py
- LDMP/calculate_lc.py
- LDMP/calculate_ldn.py
- LDMP/calculate_prod.py
- LDMP/calculate_rest_biomass.py
- LDMP/calculate_soc.py
- LDMP/calculate_tc.py
- LDMP/calculate_urban.py
- LDMP/data_io.py
- LDMP/datasets_dialog.py
- LDMP/download_data.py
- LDMP/gui/DlgAbout.ui
- LDMP/jobs/manager.py
- LDMP/jobs/mvc.py
- LDMP/landpks.py
- LDMP/lc_setup.py
- LDMP/localexecution/ldn.py
- LDMP/localexecution/totalcarbon.py
- LDMP/main_widget.py
- LDMP/plugin.py
- LDMP/processing_provider/provider.py
- LDMP/settings.py
- LDMP/utils.py
- LDMP/visualization.py
Remove all pyuic and resource dependencies to be able to run the plugin from source tree without compiling UI and resource files.
Also imports PyQt from qgis as recommended by QGIS development guidelines.
> Complete uic transition

- LDMP/gui/DlgCalculateUNCCDReport.ui
> Fix UNCCD Reporting Description Font Size

- LDMP/data/reports/full_layout_template_landscape.qpt
- LDMP/data/reports/full_layout_template_landscape_two_col_lgnd.qpt
- LDMP/data/reports/full_layout_template_portrait.qpt
- LDMP/data/reports/full_layout_template_portrait_two_col_lgnd.qpt
- LDMP/data/reports/simple_layout_template_landscape.qpt
- LDMP/data/reports/simple_layout_template_landscape_two_col_lgnd.qpt
- LDMP/data/reports/simple_layout_template_portrait _two_col_lgnd.qpt
- LDMP/data/reports/simple_layout_template_portrait.qpt
- LDMP/reports/generator.py
Fixes #641 as well as:
- Incorporate minor revisions to the templates
- Fix issue with logo (in report settings) not showing
> Report Fixes and Minor Enhancements

- .readthedocs.yaml
- README.md
- requirements-dev.txt
- tasks.py
> Publish to RTD

- LDMP/timeseries.py
Minor fix that ensures query values have been extracted before resetting the widgets.
> NDVI Query Fix

- LDMP/gui/DlgSelectDS.ui
- LDMP/jobs/manager.py
- LDMP/jobs/mvc.py
- LDMP/layers.py
- LDMP/main_widget.py
- LDMP/maptools.py
- LDMP/select_dataset.py
> False neg pos fixes

- docker/trends-earth-test-pre-scripts.sh
- test/mock/data/sample_raw_job.json
- test/test_calculate_ldn.py
Fix the current CI runs that are failing due to the `invoke` command
> Fix CI runs

- .github/workflows/staging_development.yaml
- tasks.py
Fixes https://github.com/ConservationInternational/trends.earth/issues/845
Implementation of the staging repository workflow to improve user testing. The staging repository will be available through [this link](https://raw.githubusercontent.com/ConservationInternational/trends.earth/refs/heads/release/docs/repository/plugins.xml), once the link is added as a repository inside QGIS the latest plugin development/release version will be available for users to download, test/use. 
See below screenshot on how the repository is intended to be used. More info can be found [here](https://docs.qgis.org/3.34/en/docs/training_manual/qgis_plugins/fetching_plugins.html#follow-along-configuring-additional-plugin-repositories) 
**Note**: In the screenshot above I have used a locally hosted repository …
> Staging repository setup

- LDMP/constants.py
- LDMP/definitions.py
- LDMP/gui/DlgDatasetMetadata.ui
- LDMP/metadata_dialog.py
Fixes https://github.com/ConservationInternational/trends.earth/issues/820
New look of the Dataset metadata dialog
> Updates to the metadata tool

- LDMP/calculate_ldn.py
- LDMP/reports/charts.py
Fix error in ldn_job parameters due to changes in how parameters are handled in the updated te_algorithm.
https://github.com/ConservationInternational/trends.earth-algorithms/commit/ac3179160e08054d64d483e0b4e2e1794a916dd4#diff-565d3e9e35e1cba294f84eb82786f76c06ea4e14d12d95d1b43f36a0aecb6564R227
> Fix periods key error when using latest te_algorithm

- LDMP/gui/DlgCalculateOneStep.ui
Before :
[Screencast from 2025-04-07 22-16-38.webm](https://github.com/user-attachments/assets/b076ed3b-9d12-4319-bb6a-da4e7033b23b)
After : 
[Screencast from 2025-04-07 22-15-15.webm](https://github.com/user-attachments/assets/3afc992b-0331-4e6a-a26c-1fe97dacefe2)
> Fix sub-indicator dialog pane resize issue

- LDMP/reports/models.py
Fix report not generated because template path is missing.
> Fix report not generated

- LDMP/data_io.py
to fix https://github.com/ConservationInternational/trends.earth/issues/862
@gdaldegan
> Fix import custom LD dataset

- gee/productivity/src/main.py
Fixes https://github.com/ConservationInternational/trends.earth/issues/865
> FAO WOCAT support in gee scripts

- LDMP/localexecution/soilorganiccarbon.py
There was an import that changed, a wrong file path and the vrt creation step failed for lc_final_vrt. 
Closes #901.
> fix: soil organic carbon process fails locally

- LDMP/api.py
- LDMP/areaofinterest.py
- LDMP/auth.py
- LDMP/lc_setup.py
- LDMP/worker.py
> Fix land cover class

- LDMP/calculate_drought_vulnerability.py
- LDMP/data/gee_datasets.json
- LDMP/gui/DlgCalculateDrought.ui
- LDMP/i18n/LDMP.ts
- LDMP/i18n/LDMP_ar.ts
- LDMP/i18n/LDMP_es.ts
- LDMP/i18n/LDMP_fa.ts
- LDMP/i18n/LDMP_fr.ts
- LDMP/i18n/LDMP_pt.ts
- LDMP/i18n/LDMP_ru.ts
- LDMP/i18n/LDMP_sw.ts
- LDMP/i18n/LDMP_zh.ts
Adds the possibility to choose UKCEH SPI/SPEI and CHIRPS datasets in `Drought Vulnerability` remote process.
Closes #919.
> feat: additional drought datasets

- LDMP/lc_setup.py
> fix save definition does not work

- LDMP/calculate_ldn.py
- LDMP/gui/DlgCalculateLDNSummaryTableAdmin.ui
Adds the option to consider multiple `Progress Periods` when executing `Indicator for SDG 15.3.1` local task.
Closes #938
> Add support multiple progress periods for SDG 15.3.1

- LDMP/localexecution/unccd.py
> unccd: export AOI to separate JSON file and remove it from summary

- LDMP/calculate_ldn.py
https://github.com/ConservationInternational/trends.earth/issues/967#issuecomment-3190025528
> fix: enforce_prod_date

- .github/workflows/ruff.yaml
- LDMP/calculate_ldn.py
https://github.com/ConservationInternational/trends.earth/issues/982
> Sync LC and SOC years when updating common start/end dates

- LDMP/calculate_ldn.py
https://github.com/ConservationInternational/trends.earth/issues/982#issuecomment-3207507618
> fix progress_period for local sdg task

- LDMP/settings.py
https://github.com/ConservationInternational/trends.earth/issues/982#issuecomment-3250152883
> rename import button and add tooltip

- LDMP/data/styles.json
- LDMP/layers.py
https://github.com/ConservationInternational/trends.earth/issues/996
> Remove references to 3-class FAO-WOCAT

- LDMP/lc_setup.py
https://github.com/ConservationInternational/trends.earth/issues/995#issuecomment-3309715592
> fix default LC class option color when unset
