LDMP/api.py, LDMP/gui/DlgSettings.ui, LDMP/gui/DlgSettingsEdit.ui, LDMP/gui/DlgSettingsEditForgotPassword.ui, LDMP/message_bar.py, LDMP/settings.py, LDMP/worker.py
Refactored Settings to store credentials into QGIS auth infrastructure with minimal changes in original code.
Fixes #354 #341
TODO: decide what to do with "change user" functionality. In this moment current Auth config is sores in .ini under trends_earth section. In case changing auth config this value should be changed.
=> Refactored settings GUI and logic to store credential into QGIS auth infrastructure. Fixes #354 #341

.gitignore, LDMP/__init__.py, LDMP/calculate.py, LDMP/gui/DlgSettings.ui, LDMP/gui/WidgetSelectArea.ui, LDMP/settings.py
Fixes #358
Using the mockup in https://github.com/ConservationInternational/trends.earth/issues/358 I have added a scroll area because the region content were making the setting dialogue height so large that It could fit screen.
Removed the region/point configuration in the algorithm now they are only available via Settings dialogue.
Screenshot
=> Change location of region configuration into settings dialogue

LDMP/__init__.py, LDMP/api.py, LDMP/calculate.py, LDMP/data/scripts.json, LDMP/gui/WidgetDatasetItem.ui, LDMP/jobs.py, LDMP/main_widget.py, LDMP/message_bar.py, LDMP/models/datasets.py, LDMP/models/datasets_delegate.py, LDMP/models/datasets_model.py, LDMP/plugin.py
Datasets are scanned from:
cached jobs
eventually any other josn present in base_data_directly (jumping jobs folder)
actually polling is set to 60000ms get form config: "trends_earth/advanced/refresh_polling_time"
next step are:
check for local generated Jobs/Datasets
download remote datasets
NOTE. There are some architecturally critical aspects:
A) Originally there is no difference between Job/Dataset => I hope I coded to avoid misalignments
B) Jobs=Dataset and Job list are only a API image of that available remotely => Jobs and Dataset are naturally aligned
C) Job Dataset are download in a user defined location. e.g. there is no constraint where to save datasets or job descriptors => this can be a source of misalignment.
To approach has these critical aspects:
Jobs and Datasets are sets …
=> Datasets periodic refresh and centralised Jobs/Datasets memory store management. Fixes #375

LDMP/__init__.py, LDMP/gui/WidgetDatasetItem.ui, LDMP/jobs.py, LDMP/main_widget.py, LDMP/models/datasets.py, LDMP/models/datasets_delegate.py
This PR add automatic download of datasets that are in FINISHED or SUCCESS state.
Autodownload can be disabled setting the boolean config parameter:
`trends_earth/advanced/dataset_auto_download`
that is not present is assumed True => auto download
After download download state is updated to the next Dataset refresh from base_data_directory
Downloaded dataset are not downloaded again if already downloaded BTW the original dataset json descriptor is not removed, just ignored is the equivalent downloaded json descriptor is already present.
This PR shoudl fix the following issue/features:
https://github.com/ConservationInternational/trends.earth/issues/376
https://github.com/ConservationInternational/trends.earth/issues/409
=> Automatic/configurable datasets download. Fixes #376 #409

LDMP/main_widget.py, LDMP/models/datasets.py, LDMP/models/datasets_delegate.py, LDMP/models/datasets_model.py
Fixes https://github.com/ConservationInternational/trends.earth/issues/400
Implements Datasets filtering by adding a custom sort and filtering proxy model, a subclass of  [QSortFilterProxyModel](https://doc.qt.io/qt-5/qsortfilterproxymodel.html), the subclass handles a different filtering mechanism compared to its superclass as in our case we need to filter data from Dataset class.
I have updated the model item access in the `DatasetItemDelegate` to use `Qt.DisplayRole` instead of `Qt.ItemDataRole` because the [QSortFilterProxyModel](https://doc.qt.io/qt-5/qsortfilterproxymodel.html) only support the former.
The filtering is case insensitive.
screenshot showing Datasets filtering in action
=> Datasets filtering

LDMP/gui/WidgetAlgorithmLeaf.ui, LDMP/models/algorithms_delegate.py
Fixes https://github.com/ConservationInternational/trends.earth/issues/398
Updates the algorithm run button to change according to the algorithm run mode state. 
Screenshot showing how run buttons will look accordingly to the respective algorithm run mode, the Land productivity algorithm
has been set to local and remote run modes for testing purposes.
=> Update algorithm run button

LDMP/gui/WidgetMain.ui, LDMP/main_widget.py, LDMP/models/datasets.py, LDMP/models/datasets_model.py
Fixes https://github.com/ConservationInternational/trends.earth/issues/401
Contains work from https://github.com/ConservationInternational/trends.earth/pull/423
Adds sorting functionality on the existing Datasets sort and filter proxy model, added a new Reverse checkbox that when checked the Datasets will be sorted in descending order. By default the sort in by creation date
I have added a progress message bar to notify user when Datasets sorting, this is useful when sorting take a bit long.
When datasets are refreshed and newer datasets have been added to the source model, they are automatically sorted by Date.
[**Updated**] Screenshot of sorting datasets example
=> Datasets sorting

LDMP/datasets_dialog.py
Fixes https://github.com/ConservationInternational/trends.earth/issues/456
The datasets are unloadable when they have not been downloaded or don't have local paths.
=> Disable add dataset button when the dataset can't be loaded

LDMP/jobs/manager.py
This PR makes the names of saved files more user-friendly by leading with the task name and algorithm name and placing the UUID portion last.
It also adds the job creation date to the name.
fixes #464
=> Name of saved files now puts uuid last

LDMP/calculate.py, LDMP/download_data.py, LDMP/gui/DlgDownload.ui
This PR reinstates the download of remote data which had gotten broken since some commits back, when merging the new algorithm execution dialogues
=> Fix download data dialogue

LDMP/gui/DlgCalculateLC.ui, LDMP/gui/DlgCalculateLDNSummaryTableAdmin.ui, LDMP/gui/DlgCalculateOneStep.ui, LDMP/gui/DlgCalculateProd.ui, LDMP/gui/DlgCalculateRestBiomassData.ui, LDMP/gui/DlgCalculateRestBiomassSummaryTable.ui, LDMP/gui/DlgCalculateSOC.ui, LDMP/gui/DlgCalculateTCData.ui, LDMP/gui/DlgCalculateTCSummaryTable.ui, LDMP/gui/DlgCalculateUrbanData.ui, LDMP/gui/DlgCalculateUrbanSummaryTable.ui, LDMP/gui/land_cover_setup_widget.ui, LDMP/gui/land_cover_setup_widget_local.ui, LDMP/jobs/mvc.py, LDMP/main_widget.py
This PR replaces our usage of `QRegularExpression` with `QRegExp`. This allows supporting users that have a version of Qt < 5.12
=> Use qregexp in order to support older qt versions

LDMP/datasets_dialog.py
Sets the export button state based on whether the result local paths exists or not.
=> Disable export button when the local paths does not exists

LDMP/data/gee_datasets.json
Didn't notice that there was a parenthesis mistakenly placed at the GPW v411 gee dataset address.
=> removes parenthesis from GPW gee dataset address

LDMP/layers.py
Old QGIS versions show popup when style saved under the same name, so we have to drop it before saving.
=> drop existing style from the GPKG (fix #587)

LDMP/timeseries.py
Hi,
Thanks for all your work on Trends.Earth! I've faced an error loading the plugin on Linux because it uses case-sensitive paths. Here is a fix.
=> Fix loading DlgTimeseries.ui on Linux

LDMP/worker.py
Setting a QProgressBar to a float value raises an exception on Python 3.9 +
=> Fix exception on newer python versions

LDMP/jobs/manager.py
Fix for https://github.com/ConservationInternational/trends.earth/issues/738
These changes ensure that jobs are only set with results extent when the results are avaialable, this  also prevents accessing `None` results which can lead to `AttributeError`.
=> Fix error in setting job extent

LDMP/conf.py, LDMP/lc_setup.py
fixes #725 
The degradation landcover table will now increase in size as the number of rows increases - this will avoid an additional scroll bar for the table:
If there are 5 or less rows in the table, the row height will be set to 40. The value 40 is used because its the lowest value that can be used, due to the minimum value based on the font used for the table cells.
=> Dev landcover matrix

LDMP/calculate.py
fixes #747 
Changed the code back to handling the no buffer error to the original code:
Removed the added (+ green) lines and readded the removed lines (- red)
@azvoleff Let me know if this resolved the problem. This is now the original approach so if this worked fine in the past it should not be an issue.
=> Replaced the not buffer error handling with the original approach.

LDMP/algorithms/mvc.py, LDMP/conf.py, LDMP/gui/WidgetSettingsAdvanced.ui, LDMP/jobs/manager.py, LDMP/jobs/mvc.py, LDMP/main_widget.py, LDMP/plugin.py, LDMP/settings.py
fixes #697 
Adds offline mode support to the plugin. The user can enable the offline mode by going to the Trends.Earth options, in the Advanced section.
Login info disabled
Remote algorithms are disabled:
- The dock title will change to "Trends.Earth (offline mode)".
- Periodic calls to the server (e.g. refresh data list) is disabled.
- Download dataset button disabled
- Remote processes will no longer be displayed in the list. Disabling offline mode and clicking refresh will show them again
=> Offline mode support

LDMP/api.py, LDMP/download.py, LDMP/gui/DlgSettings.ui, LDMP/settings.py
Fixes in https://github.com/ConservationInternational/trends.earth/issues/692
These changes are from on @vermeulendivan work in branch https://github.com/vermeulendivan/trends.earth/tree/dev_migrate_qgsnetwork.
They contain updates from usage of `requests` package to `QgsNetworkAccessManager` in making plugins network requests.
=> Migration to QgsNetworkAccessManager

.github/workflows/ruff.yaml
Excludes the GEE library https://github.com/ConservationInternational/trends.earth-gee when checking for repository code formatting.
=> Update on code format workflow

.github/workflows/staging_release.yaml
Fixes https://github.com/ConservationInternational/trends.earth/issues/845
Changes to update the staging repository when a new official plugin release is added in release page.
Depends on https://github.com/ConservationInternational/trends.earth/pull/847
=> Staging repository updates

.github/workflows/pr_package.yml
Adds new workflow for handling plugin zip file that can be used to check/test/confirm the proposed changes in the PR before merging the PR into the repository.
Screenshot of the comment with a link to the plugin zip file
=> Workflow for creating plugin zip artifact on pull requests

LDMP/conf.py, LDMP/dataset_additional_metadata.py, LDMP/download_data.py, LDMP/gui/DlgDatasetAdditionalMetadata.ui, LDMP/gui/WidgetMain.ui, LDMP/jobs/mvc.py, LDMP/main_widget.py
Fixes https://github.com/ConservationInternational/trends.earth/issues/819.
Adds a new date filter group box with input for start and end datetime used to filter the datasets list and a dialog for additional metadata from the download tool
Screenshot of the date filter group box
Screenshot of the additional metadata group box
=> Enable date filtering in the datasets items

LDMP/conf.py, LDMP/gui/DlgCalculateOneStep.ui, LDMP/gui/WidgetLCClassManage.ui, LDMP/lc_setup.py, LDMP/settings.py
Fixes https://github.com/ConservationInternational/trends.earth/issues/823
The new `Import` button under the Custom Land classes group box provides an option to select a `CSV` file and then opens a dialog that allows assignment of parents into the new class names.
The new import button in the Land Cover tool buttons
Screenshot of a CSV  file and the resulting import dialog look.
|File|Dialog|
|-----------------------|--------------------------|
|![image](https://github.com/user-attachments/assets/a19f360c-e834-4a15-81c0-75ba58baa0b0) | ![image](https://github.com/user-attachments/assets/45ae19a5-ae8b-47db-916f-801cbeed49e6)|
=> Support for class names import 

LDMP/calculate_ldn.py, LDMP/gui/DlgCalculateOneStep.ui, LDMP/gui/DlgTimelinePeriodGraph.ui
For https://github.com/ConservationInternational/trends.earth/issues/856
https://github.com/user-attachments/assets/4536dc22-8c5d-469d-8e37-33cf571b5686
=> Add graph based on for time period comparison

LDMP/lc_setup.py
Fixes https://github.com/ConservationInternational/trends.earth/issues/827
Makes sure the LC transition matrix table is fully reset when user click the "Reset table" button
Screenshot
=> Fix LC transition matrix table reset

.github/workflows/comment_pr_package.yaml
Update the used PR package workflow name, from  ` Creating plugin package in the PR` to  `Create plugin package in the PR`
=> Fix the comments creation workflow

requirements.txt
If we continue using 8.7.0, it will cause a dependency conflict
=> Update marshmallow_dataclass to version 3.7.1

LDMP/calculate_urban.py
The `DlgCalculateUrbanSummaryTable` class was trying to get the bands for iteration from the `bands` attribute of the class `RasterResults`. `bands` is not an attribute of `RasterResults`, but the classes bands can be received using its `get_bands()` method. This method is now used to get the bands to iterate over. 
Closes #902.
=> fix: urban change summary table for city process fails to run

LDMP/calculate_soc.py
Removes the unused `te_schemas.land_cover.LCTransitionDefinitionDeg` import.
Closes #924
=> fix: remove unused import statement in calculate_soc.py

LDMP/data_io.py
Improves both the performance of raster and land cover data imports. The output data type for raster imports has been changed to Byte to optimize file size. This is while switching from GDAL `build_vrt` to `translate`. Additionally, the land cover import process now uses multi-threading. 
Execution was sped up time by approximately 45%. Tested on a 50km buffer area resampling from 30m to 300m. 
Closes #816, since the original issue was import speed of land cover data.
=> fix: improve landcover data import speed

LDMP/calculate_ldn.py
The index of the `comboBox` needed to be set prior to accessing its text. 
Closes #942.
=> fix: key error with reporting period default selection

LDMP/calculate_ldn.py
- [update timeline graph on apply_preset](https://github.com/ConservationInternational/trends.earth/commit/a7d986ec71e29018fb56bae76d52c9b5e203a18a)
- [fix inconsistency with JRC pre-calculated LPD](https://github.com/ConservationInternational/trends.earth/commit/16bc4b0c93a9c6fccb3a79ba96f1c2a18865f9af)
=> fixes for #995
